### ISSUE TITLE
Looking for an example of how to use the compile and dispatch pipe functionality

### ISSUE THREAD

**Issue by jt269** [vinci1it2000/formulas#123]
Hello,

I have a complex excel model with which I would like to run many iterations on. I am interested in the compile and dispatch pipe functionality but I can't see how to return and record the results using a loop to change the input cell each time.

In addition, it takes a long time (and a lot of memory) to load my model even from a .json file, is there any way to speed this up? Can I save a compiled model somehow and use that without having to load the model from the .json each time?

Any help appreciated, Thanks.

**Comment by vinci1it2000** [comment]
Hi, thanks for your question!

You're absolutely on the right path using the `compile` and `dispatch` features of the `formulas` library — they're designed specifically for running large numbers of iterations efficiently over complex Excel models.

I've attached the files needed to reproduce the case described below.
You can run the script directly to test loading, compiling, parallel execution, and exporting the results to CSV.

[Archive.zip](https://github.com/user-attachments/files/19614944/Archive.zip)

---

###  Improving Load Time and Reducing Memory Usage

Rather than loading the full model from `.json` or `.xlsx` each time (which can be slow and memory-intensive), you can streamline the process using the following approach:

#### 1. Load only the necessary ranges

Instead of parsing the entire file, load only the relevant functions to compute the outputs using  `from_ranges()`. For example:

```python
fpath = "excel.xlsx"
xl_model = formulas.ExcelModel().from_ranges(
    "'[%s]DATA'!C2:C4" % fpath  # Output cells
).finish()
```

#### 2. Compile and save the model using `dill`

Once compiled, you can serialize the function for reuse:

```python
compiled_func = xl_model.compile(
    inputs=[
        "'[%s]DATA'!A2" % fpath,
        "'[%s]DATA'!A3" % fpath,
        "'[%s]DATA'!A4" % fpath
    ],
    outputs=[
        "'[%s]DATA'!C2" % fpath,
        "'[%s]DATA'!C3" % fpath,
        "'[%s]DATA'!C4" % fpath
    ]
)

with open("model.dill", "wb") as f:
    dill.dump(compiled_func, f)
```

#### 3. Load the compiled model in your workers

Set a global function and define an initializer for multiprocessing:

```python
func = None

def load_model(path):
    global func
    with open(path, "rb") as f:
        func = dill.load(f)
```

This setup avoids reloading or recompiling the model in every iteration, making your simulations much faster.

---

###  Running Iterations in Parallel and Recording Results

After compiling and saving the model, you can run simulations in parallel. Here's a complete example:

#### Define your inputs and batch them

```python
input_values = [(i * 0.1, i * 0.2, i * 0.4) for i in range(1000)]

def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

batches = list(chunks(input_values, 100))  # Batch size = 100
```

#### Evaluate batches using multiprocessing

```python
from multiprocess import Pool
import time
import psutil
import pandas as pd

def evaluate_batch(batch):
    return [tuple(v.value[0][0] for v in func(*vals)) for vals in batch]

if __name__ == '__main__':
    print("Saving model...")
    save_model("model.dill")

    print("Starting multiprocessing evaluation...")

    with Pool(initializer=load_model, initargs=("model.dill",)) as pool:
        results_nested = pool.map(evaluate_batch, batches)

    results = [item for sublist in results_nested for item in sublist]

    # Export to CSV
    df = pd.DataFrame(results, columns=["C2", "C3", "C4"])
    df.to_csv("results.csv", index=False)
    print("Results saved to results.csv")
```

---

###  Summary

- Use `from_ranges()` to load only what you need.
- Compile once and save using `dill`.
- Use `multiprocess` with batch processing for performance.

**Comment by BiboyQG** [comment]
> may i ask for a pip freeze to run the code above ? i am having this error:
> 
> ```
> Saving model...
> Traceback (most recent call last):
>   File "c:\Users\..\Downloads\Archive\run.py", line 73, in <module>
>     save_model("model.dill")
>   File "c:\Users\..\Downloads\Archive\run.py", line 26, in save_model
>     xl_model = formulas.ExcelModel().from_dict(
>   File "C:\Users\..\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\formulas\excel\__init__.py", line 491, in from_dict
>     for k, v in adict.items():
> AttributeError: 'str' object has no attribute 'items'
> ```

This is because there's actually a bug in the code inside `Archive.zip`. If you change `xl_model = formulas.ExcelModel().from_dict(` to `xl_model = formulas.ExcelModel().from_ranges(`, everything should be good.

**Comment by dberardo-com** [comment]
unrelated questions here:

* i assume the same approach as above can be easily used to do sequencial evaluation of excels rather than parallel one right? i mean when the results of one iteration as fed back as input to the next excel evaluation and so on ?
* is it possible to make use of the SOLVER capabilities of excel ? or are those some sort of wrapper functionalities of excel which are not available directly in formulas ? By solver i mean linear programming or integer programming and so on

cheers
