### ISSUE TITLE
Formula `=5%` cannot be parsed

### ISSUE THREAD

**Issue by KentCai01** [vinci1it2000/formulas#20]
**Describe the bug**
Formulas like `=5%` cannot be parsed.

**To Reproduce**

```
>>>import formulas
>>> formulas.Parser().ast('=5%')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Apps\Continuum\miniconda3\lib\site-packages\formulas\parser.py", line 68, in ast
    builder.finish()
  File "D:\Apps\Continuum\miniconda3\lib\site-packages\formulas\builder.py", line 80, in finish
    self.get_node_id(token)
  File "D:\Apps\Continuum\miniconda3\lib\site-packages\formulas\builder.py", line 71, in get_node_id
    kw['default_value'] = token.compile()
  File "D:\Apps\Continuum\miniconda3\lib\site-packages\formulas\tokens\operand.py", line 66, in compile
    return eval(self.name.capitalize())
  File "<string>", line 1
    5%
     ^
SyntaxError: unexpected EOF while parsing
```

**Comment by vinci1it2000** [comment]
This has been fixed with the latest release 0.1.4.
