### ISSUE TITLE
Enable full column and row reference

### ISSUE THREAD

**Issue by shirisha95** [vinci1it2000/formulas#24]
**VLOOKUP doesn't work**
 Vlookup from one sheet to another throws 'negative dimensions are not allowed'

1. Sample file
[Book1.xlsx](https://github.com/vinci1it2000/formulas/files/2801943/Book1.xlsx)
2. Sample Code:
[sample.txt](https://github.com/vinci1it2000/formulas/files/2801949/sample.txt)
3. Error - Stack trace
Failed DISPATCHING '='[BOOK.XLSX]SHEET2'!A:B' due to:
  ValueError('negative dimensions are not allowed',)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/schedula/utils/sol.py", line 748, in _set_function_node_output
    res = self._evaluate_function(args, node_id, node_attr, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/schedula/utils/sol.py", line 533, in _evaluate_function
    res = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/formulas/cell.py", line 166, in __call__
    return _assemble_values(base, values, sh.EMPTY)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/formulas/ranges.py", line 103, in _assemble_values
    res = np.empty(_shape(**base), object)
ValueError: negative dimensions are not allowed

**Expected behavior**
VLOOKUP is to be evaluated

**Comment by vinci1it2000** [comment]
As I mention in the email the problem is not the VLOOKUP but just the range definition. Ranges like A:B or 1:6 (i.e. **full column or row reference**) are not fully supported in this version. 

If you are on rush I suggest to modify the excel file specifying the range as `A1:B4`. Otherwise, I'm working to solve it.
