### ISSUE TITLE
Hasn't the DATE function been implemented?

### ISSUE THREAD

**Issue by hao276843248** [vinci1it2000/formulas#36]
a = '=DATE(1,1,1)'
func = formulas.Parser().ast(a)[1].compile()
print("inputs\t" + str(list(func.inputs)))

inputs	[]
Failed DISPATCHING 'DATE' due to:
  FunctionError('Function not implemented!',)
Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\schedula\utils\sol.py", line 620, in _evaluate_node
    **kw)
  File "C:\Python\Python36\lib\site-packages\schedula\utils\sol.py", line 594, in _evaluate_function
    sol=self, callback=_callback, sol_name=self.full_name + (node_id,)
  File "C:\Python\Python36\lib\site-packages\schedula\utils\asy.py", line 167, in async_process
    name, funcs, executor, *args, **kw
  File "C:\Python\Python36\lib\site-packages\schedula\utils\asy.py", line 124, in _process_funcs
    r['res'] = e.process(fn, *args, **kw) if e else fn(*args, **kw)
  File "C:\Python\Python36\lib\site-packages\formulas-0.3.0-py3.6.egg\formulas\functions\__init__.py", line 81, in not_implemented
    raise FunctionError()
formulas.errors.FunctionError: Function not implemented!

**Comment by vinci1it2000** [comment]
Some `DATE & TIME` functions are now implemented.
