### ISSUE TITLE
No module named 'regex._regex' when try to run example

### ISSUE THREAD

**Issue by 2017jw** [vinci1it2000/formulas#56]
**Describe the bug**
ModuleNotFoundError: No module named 'regex._regex'

**To Reproduce**
```python
>>> import formulas
>>> func = formulas.Parser().ast('=(1 + 1) + B3 / A2')[1].compile()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\formulas\__init__.py", line 68, in __getattr__
    obj = getattr(importlib.import_module(_all[name], __name__), name)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\formulas\parser.py", line 14, in <module>
    import regex
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\regex\regex.py", line 403, in <module>
    import regex._regex_core as _regex_core
  File "C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'
```

**Desktop:**
 - OS: Windows 10, python 3.8 x64
 - Version 1.0

**Comment by 2017jw** [comment]
seems like a regex issue, had found solution [here](https://github.com/psf/black/issues/1207#issuecomment-566239119)

**Comment by vinci1it2000** [comment]
Closing since you had the solution.
