### ISSUE TITLE
FORECAST excel formula not implemented.

### ISSUE THREAD

**Issue by pavanavap** [vinci1it2000/formulas#80]
When we are evaluating the formulas module to evaluate excel files on Linux system.
While doing so, we have encountered an excel formula FORECAST which was not implemented,

Below is the code snippet I was executing.

>>> func = formulas.Parser().ast('=FORECAST(A1, B2:B5,C2:C5)')[1].compile()
>>> func
<schedula.utils.dsp.DispatchPipe object at 0x0000015F5FE43848>
>>> func(0.21, [0.21,0.291,0.328,0.396], [0.0217,0.0474,0.050457757,0.062])

The result should be **0.024828**
The below is the exception that is being displayed:

_Traceback (most recent call last):
  File "C:\Platform\Python37\lib\site-packages\schedula\utils\sol.py", line 632, in _evaluate_node
    **kw)
  File "C:\Platform\Python37\lib\site-packages\schedula\utils\sol.py", line 606, in _evaluate_function
    verbose=self.verbose
  File "C:\Platform\Python37\lib\site-packages\schedula\utils\asy\__init__.py", line 179, in async_process
    exe_id, funcs, executor, *args, **kw
  File "C:\Platform\Python37\lib\site-packages\schedula\utils\asy\__init__.py", line 136, in _process_funcs
    r['res'] = e.process(sid, fn, *args, **kw) if e else fn(*args, **kw)
  File "C:\Platform\Python37\lib\site-packages\formulas\functions\__init__.py", line 101, in not_implemented
    raise NotImplementedError
NotImplementedError_

Is there a plan to get this formula implemented in the future releases?

[Book1.xlsx](https://github.com/vinci1it2000/formulas/files/6537182/Book1.xlsx)

**Comment by vinci1it2000** [comment]
Implemented into the current dev:

```
>>> import formulas
>>> func = formulas.Parser().ast('=FORECAST(A1, B2:B5,C2:C5)')[1].compile()
>>> func(0.21, [0.0217,0.0474,0.050457757,0.062], [0.21,0.291,0.328,0.396])
Array(0.02482833205463321, dtype=object)
```
