### ISSUE TITLE
AttributeError: 'Worksheet' object has no attribute 'formula_attributes'

### ISSUE THREAD

**Issue by qxtaiba** [vinci1it2000/formulas#88]
**Describe the bug**

I'm getting an AttributeError when running the Excel Workbook model found in the README of this repo. 

**To Reproduce**

Follow the steps outlined in REDAME to reproduce. 

1. install formulas using pip 
2. follow steps for Excel workbook example
3. See error

**Expected behavior**

It should just run. 

**Error**

>>> xl_model = formulas.ExcelModel().loads(fpath).finish()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/qalnuaimy/Library/Python/3.8/lib/python/site-packages/formulas/excel/__init__.py", line 94, in loads
    self.load(filename)
  File "/Users/qalnuaimy/Library/Python/3.8/lib/python/site-packages/formulas/excel/__init__.py", line 99, in load
    self.pushes(*book.worksheets, context=context)
  File "/Users/qalnuaimy/Library/Python/3.8/lib/python/site-packages/formulas/excel/__init__.py", line 107, in pushes
    self.push(ws, context=context)
  File "/Users/qalnuaimy/Library/Python/3.8/lib/python/site-packages/formulas/excel/__init__.py", line 111, in push
    worksheet, context = self.add_sheet(worksheet, context)
  File "/Users/qalnuaimy/Library/Python/3.8/lib/python/site-packages/formulas/excel/__init__.py", line 180, in add_sheet
    k: v['ref'] for k, v in worksheet.formula_attributes.items()
AttributeError: 'Worksheet' object has no attribute 'formula_attributes'

**Desktop (please complete the following information):**

 - OS: MacOS
 - Version: Catalin 10.15.7

**Additional context**

I'm running Python3.8.2 and reproduced this error on both excel.xlsx and my own files

**Comment by qxtaiba** [comment]
afaik since openpyxl's latest update (10.09.2021, 3.0.8 in [this](https://foss.heptapod.net/openpyxl/openpyxl/-/commit/b71b6ba667e9fcf8de3f899382d446626e55970c) commit) the formula_attributes mentioned above have been removed, which means that the ExcelModel does not work anymore since the libraries seem to be incompatible at the moment

**Comment by vinci1it2000** [comment]
`openpyxl==3.0.8` is now retracted
